### ISSUE TITLE
Errors installing gatsby-remark-code-buttons

### ISSUE THREAD

**Issue by nstahl** [iamskok/gatsby-remark-code-buttons#5] opened 2019-09-18 21:08 UTC
Hi, I'm trying to install the plugin with 

`npm install gatsby-remark-code-buttons --save-dev`

but the build fails with the following error message

```
31 warnings and 9 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/nstahl/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/Users/nstahl/.nvm/versions/node/v12.10.0/bin/node" "/Users/nstahl/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/nstahl/Code/docsite/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/nstahl/Code/docsite/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64" "--napi_version=4" "--node_abi_napi=napi"
gyp ERR! cwd /Users/nstahl/Code/docsite/node_modules/fsevents
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/nstahl/.nvm/versions/node/v12.10.0/bin/node /Users/nstahl/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/nstahl/Code/docsite/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/nstahl/Code/docsite/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=4 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/nstahl/Code/docsite/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 18.6.0
node-pre-gyp ERR! command "/Users/nstahl/.nvm/versions/node/v12.10.0/bin/node" "/Users/nstahl/Code/docsite/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/nstahl/Code/docsite/node_modules/fsevents
node-pre-gyp ERR! node -v v12.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
node-pre-gyp ERR! not ok 
```

Thanks for your help!

**Comment by nstahl** [comment] 2019-09-18 21:08
```
node -v
v12.10.0
```

**Comment by iamskok** [comment] 2019-09-19 01:38
@nstahl I don’t see the error say anything about `gatsby-remark-code-buttons`. It looks like the problem is related to your NVM setup. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnstahl** [comment] 2019-09-19 02:50
Thanks @iamskok. The setup works fine until I add the `gatsby-remark-code-buttons` plugin. Any advice you have on debugging would be appreciated.

**Comment by iamskok** [comment] 2019-09-19 03:16
Removing package-lock.json / yarn.lock and node_modules should help.

I’m going to close this issue. Feel free to reach out in twitter.com/iamskok 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed** 2019-09-19 03:18 UTC
